// Side quests: "envelope" notes scattered off the main path. A note reveals on
// a runner's map once their personal miles reach `revealMiles`; opening it moves
// it off the map and into the backpack, grouped by its `arc` (story thread).
//
// Each note belongs to an arc (see ARCS for the display title + envelope glow
// color). "general" notes are one-off flavor (white glow). Positions are in the
// map image's pixel space (1448 x 1086) and were placed just off the drawn path
// near each note's reveal point.
export type QuestArc =
  | "general" | "smeagol" | "bilbo" | "bombadil" | "dwarves" | "elves" | "wizards" | "faramir" | "orcs";

export interface SideQuest {
  id: string;
  arc: QuestArc;
  revealMiles: number;
  x: number;
  y: number;
  title: string;
  story: string;
  photo?: string;
}

export interface ArcInfo {
  title: string;
  color: string;
}

// Display title + envelope glow color for each story thread.
export const ARCS: Record<QuestArc, ArcInfo> = {
  general: { title: "Notes Along the Way", color: "#ffffff" },
  smeagol: { title: "Sméagol → Gollum", color: "#7cb342" },
  bilbo: { title: "Bilbo: There and Back Again", color: "#e0a323" },
  bombadil: { title: "Tom Bombadil: The Eldest", color: "#ffe14d" },
  dwarves: { title: "The Dwarves of Moria", color: "#cc6600" },
  elves: { title: "The Elves", color: "#7ec8e3" },
  wizards: { title: "The Istari", color: "#9c6ade" },
  faramir: { title: "Faramir of Gondor", color: "#2e8b7a" },
  orcs: { title: "The Orcs of Mordor", color: "#c0392b" },
};

export const SIDE_QUESTS: SideQuest[] = [
  { id: "general-1", arc: "general", revealMiles: 5, x: 145, y: 333, title: "A Handkerchief on the Hedge", story: "Snagged on a hedge at the very edge of town, a clean handkerchief and a hastily-pinned note: “You forgot this — as usual. Take it, and take heart. The first mile is the hardest, and you've already begun. Off you go, and mind the puddles.”" },
  { id: "smeagol-1", arc: "smeagol", revealMiles: 12, x: 147, y: 323, title: "A Birthday by the River", story: "Long before your road began, the Stoor-folk fished the reed-banks of the Great River. On Sméagol's birthday his kinsman Déagol was dragged under by a great fish and came up clutching a ring of gold, bright out of the black mud. “Give us that, Déagol, my love,” said Sméagol. “Why?” “Because it's my birthday, and I wants it.”" },
  { id: "bilbo-1", arc: "bilbo", revealMiles: 30, x: 152, y: 297, title: "An Unexpected Party", story: "One grey morning a wizard scratched a secret mark on a green door in the Shire, and by evening thirteen dwarves had eaten Bilbo Baggins out of house and home. Before he quite knew how, he had run out his door without so much as a pocket-handkerchief, hired as “burglar” on a quest to a mountain far in the East. He grumbled the whole first mile — and never regretted a step." },
  { id: "general-2", arc: "general", revealMiles: 50, x: 224, y: 233, title: "A Waymeet Signpost", story: "A weathered signpost leans where two paths cross, its arms pointing to places with cheerful, half-familiar names. Someone has carved a small message into the post: “You're off, then. Mind your feet, keep some food in your pack, and don't forget to look back at the green country now and again.”" },
  { id: "general-3", arc: "general", revealMiles: 130, x: 196, y: 402, title: "A League-Stone", story: "A squat mossy stone leans in the long grass, a numeral chiseled on its face and long since softened by rain. It once told travelers how far to the next inn and a warm bed. Now it simply says, in effect: you have come this far, and that is something worth a nod." },
  { id: "bilbo-2", arc: "bilbo", revealMiles: 150, x: 294, y: 261, title: "Trolls and a Lucky Dawn", story: "Early on the road east, three great trolls caught the whole company and fell to arguing over how to cook them — boiled, minced, or simply sat upon. Gandalf, hidden in the dark, threw his voice and kept the trolls squabbling until dawn broke over the hill and turned all three to stone, as trolls always do if caught above ground by the sun. In their cave-hoard Bilbo found a small, ancient blade — just his size — that he would one day name Sting." },
  { id: "wizards-1", arc: "wizards", revealMiles: 180, x: 222, y: 400, title: "Five Came Over Sea", story: "In the world's middle years the Powers of the West sent five to contest the Shadow — the Istari, wizards clad as old men, their strength veiled. They were forbidden to match Sauron power for power, or to rule the peoples of Middle-earth; they came to counsel, to kindle courage, and to stir hearts against the dark. Old and grey they wandered, and few guessed what they truly were." },
  { id: "smeagol-2", arc: "smeagol", revealMiles: 210, x: 316, y: 274, title: "The Birthday Present", story: "Déagol would not give the present, so Sméagol's hands found his throat — the gold was already whispering. He hid the body and learned to hide himself: to creep, to lie, to hate the sun. When his own grandmother cast him from her hole and his kin drove him out with stones, he crept down into the cold roots of the mountains, alone with the precious." },
  { id: "general-4", arc: "general", revealMiles: 230, x: 261, y: 377, title: "The Scarecrow's Hat", story: "A cheerful scarecrow guards a field just off the road, wearing a battered hat at a jaunty angle. A note is tucked in its straw sleeve: “Mind the crows if you rest here — and whatever you do, the mushrooms in the far corner belong to Farmer Maggot. He knows. He always knows.”" },
  { id: "bombadil-1", arc: "bombadil", revealMiles: 235, x: 325, y: 280, title: "Eldest", story: "Before the Shire, before the kingdoms of Men, before even the Elves first looked on the stars, Tom Bombadil was already here. He is the Eldest, he says — fatherless, he remembers the first raindrop and the first acorn, and knew the dark under the sky when it was fearless, before the Dark Lord came from Outside. Rivers and trees and hills have his measure, for he was here before them all." },
  { id: "bilbo-3", arc: "bilbo", revealMiles: 250, x: 268, y: 381, title: "A Ring in the Dark", story: "Lost in the goblin-tunnels beneath the Misty Mountains, Bilbo's hand found a small cold ring in the dark and slipped it in his pocket. He won it, more or less fairly, in a game of riddles with a wretched creature by an underground lake — and when he might have killed the poor thing to escape, pity stayed his hand. That mercy, he never knew, would one day matter more than all the dragon's gold." },
  { id: "general-5", arc: "general", revealMiles: 320, x: 338, y: 271, title: "The Old Stone Bridge", story: "A little humpbacked bridge of grey stone crosses a chattering stream, older than anyone hereabouts remembers building. Generations of travelers have scratched their initials into the parapet, some so worn they are only dents now. Add yours if you like — the bridge has always had room for one more." },
  { id: "general-6", arc: "general", revealMiles: 380, x: 432, y: 370, title: "A Traveler's Cache", story: "A little cairn of stones stands just off the road, and tucked beneath the top one is a scrap of waxed cloth around half a seed-cake. A note in a round hand reads: “For whoever comes after — the road is long and second breakfast is a virtue, not a vice. Courage.”" },
  { id: "bombadil-2", arc: "bombadil", revealMiles: 400, x: 454, y: 255, title: "Goldberry, the River-daughter", story: "In Tom's low house beyond the Old Forest dwells Goldberry, fair as the first warm day of spring, her gown green as young reeds and her voice like water running over stones. She is the River-woman's daughter, drawn up out of the deep pools of the Withywindle. When she sings, the rain falls soft and the whole year seems to turn gentle, and travelers who meet her are never quite sure, afterward, that they did not dream her." },
  { id: "smeagol-3", arc: "smeagol", revealMiles: 455, x: 446, y: 383, title: "Gollum, Gollum", story: "Under the Misty Mountains he found a cold, dark lake, and there the years drowned one into the next — hundreds of them. The Ring kept him thin and stretched and old past dying, and he talked to himself in two voices, for he had no one else. Gollum, gollum, went the swallowing in his throat, and so the deep-fearing folk named him." },
  { id: "elves-1", arc: "elves", revealMiles: 468, x: 492, y: 278, title: "The Last Homely House", story: "East of the Sea and west of the Mountains stands Rivendell, the house of Elrond Half-elven — a refuge of song, healing, and long memory, where the weary find rest and the counsel of ages. Elrond has seen three thousand years turn; he remembers the Last Alliance of Elves and Men, and the fall of Gil-galad his lord. In his valley the tide of the world seems, for a while, to pause." },
  { id: "bilbo-4", arc: "bilbo", revealMiles: 500, x: 498, y: 396, title: "The Dragon and the Mountain", story: "Under the Lonely Mountain, Bilbo matched wits with Smaug the Golden — cleverest and greediest of dragons — and lived to tell it. He found the Arkenstone, the heart of the mountain, and gave it away to keep the peace, then watched dwarves, elves, and men nearly come to war over the hoard until goblins and wolves forced them to stand together. He came home with treasure, a coat of mithril, and a story: There and Back Again." },
  { id: "wizards-2", arc: "wizards", revealMiles: 515, x: 525, y: 282, title: "The White and the Grey", story: "Saruman the White was chief of the order, deepest in the lore of the Rings — and it was that very study that undid him, for he came to covet the power he was sent to oppose. Gandalf the Grey held no fortress and sought no throne; he wandered, lighting fires in cold hearts, trusted by the small and the overlooked. In the end the one who grasped for power fell, and the one who gave it away prevailed." },
  { id: "general-7", arc: "general", revealMiles: 540, x: 525, y: 400, title: "A Walking-Song", story: "A scrap of paper, weighted under a stone, carries a few lines of a walking-song in a looping hand: “The Road goes ever on and on, down from the door where it began…” The rest is smudged away by rain. Whoever wrote it plainly meant to keep walking, and to hum as they went." },
  { id: "bombadil-3", arc: "bombadil", revealMiles: 605, x: 584, y: 291, title: "Master of Wood and Water", story: "In a snug house between the Old Forest and the Barrow-downs, Tom lives with Goldberry, the River-woman's daughter, and fears nothing under sun or stars. He sings nonsense that bends the world to kindness — freeing hobbits from Old Man Willow, driving off the cold barrow-wights — for he is Master here, though he owns nothing and rules no one. His country's borders are small, and he will not step beyond them." },
  { id: "elves-2", arc: "elves", revealMiles: 640, x: 587, y: 409, title: "The Three Rings", story: "The Elves forged Three Rings of their own — Vilya, Nenya, and Narya — and these Sauron's hand never touched, so they remained unstained. With them the Elves held off the wearing of time, preserving Rivendell, the Golden Wood, and much that is fair. Yet all Three are bound to the One; should it fall, they fail too, and all they shelter must fade. The Elves knew this — and chose to help destroy it anyway." },
  { id: "general-8", arc: "general", revealMiles: 660, x: 616, y: 296, title: "A Cairn for the Road", story: "A knee-high cairn of stones stands at a lonely turning, and it is plain from the many hands' work that each traveler who passes adds one to the pile. A note weighted beneath the base reads: “One stone for one safe mile. Leave one, take courage, keep going.”" },
  { id: "smeagol-4", arc: "smeagol", revealMiles: 690, x: 617, y: 413, title: "Riddles in the Dark", story: "Then a soft-footed thief came into his dark — a Baggins, though he did not yet know the name. They played the riddle-game on the shore of the black water, wits for a life, and when Gollum crept to fetch his birthday-present to cheat, it was gone. Gone! “Thief, thief, Baggins! We hates it, we hates it forever!” But the thief had already slipped away, and the precious with him." },
  { id: "wizards-3", arc: "wizards", revealMiles: 700, x: 634, y: 299, title: "Olórin", story: "Long before he was Gandalf the Grey, in the deathless land in the West, he was Olórin — wisest of the Maiar, who dwelt in the gardens of the Powers and learned there pity and patience. He walked unseen among the Elves, it is said, putting courage and fair visions into their hearts. Of all the five sent into Middle-earth, he alone never sought a home, a fortress, or a throne, but wandered as a grey stranger, kindling hope and asking nothing for himself." },
  { id: "general-9", arc: "general", revealMiles: 730, x: 663, y: 409, title: "An Empty Camp", story: "The ashes of a campfire are still faintly warm, and the grass is pressed where someone slept only hours ago. A single boot-print points onward up the road, and a stick has been driven into the ground beside it — a traveler's old sign meaning simply: this way is safe, keep going." },
  { id: "bilbo-5", arc: "bilbo", revealMiles: 758, x: 654, y: 292, title: "The Long-Expected Party", story: "On his eleventy-first birthday Bilbo threw the grandest party the Shire had ever seen, made a little speech, slipped on his ring, and vanished — off at last to see mountains again. It cost him dearly to leave the ring behind for his heir Frodo; his hand did not want to let it go. He settled in Rivendell among the elves to finish his book, asking only for news of the wide world and one more song before bed." },
  { id: "bombadil-4", arc: "bombadil", revealMiles: 795, x: 699, y: 402, title: "The Barrow-wights", story: "On the cold Barrow-downs lie the bones of forgotten kings, and among the green mounds crept the barrow-wights — chill spirits sent long ago out of the dark North to haunt the dead. They lure the living down into the barrows to lie among gold and grow cold forever. But no wight can hold what is Tom's: he strides in singing, “Get out, you old Wight! Vanish in the sunlight!” — and the deathly cold breaks apart like river-ice in spring." },
  { id: "dwarves-1", arc: "dwarves", revealMiles: 805, x: 704, y: 287, title: "The Doors of Durin", story: "The western door of Moria was raised in the old friendship of Elves and Dwarves — Narvi the Dwarf wrought it, and Celebrimbor the Elf drew it in ithildin, which gives back only the light of moon and stars. Across it ran an inscription that read like a riddle: “Speak, friend, and enter.” The wise puzzled over secret passwords and spells for hours — when all along the answer was simply to say the Elvish word for friend, mellon, and the great doors would swing wide." },
  { id: "dwarves-2", arc: "dwarves", revealMiles: 812, x: 691, y: 402, title: "The Glory of Khazad-dûm", story: "Once this was no black pit but Khazad-dûm, the mightiest mansion of Dwarves that ever was — hall upon hall, stair upon stair, delved down the roots of the mountains and lit like a city of lamps. Here Durin the Deathless woke at the world's dawn, and here his folk mined mithril, true-silver, worth more than a king's ransom and light as a feather. For an age it was the wonder of the North." },
  { id: "dwarves-3", arc: "dwarves", revealMiles: 862, x: 758, y: 299, title: "Too Greedy, Too Deep", story: "Digging ever downward for mithril, the Dwarves delved too greedily and too deep, and woke a thing that had slept since the making of the world — a Balrog, a demon of shadow and flame out of the first Dark Lord's ruin. It slew Durin's heir, and the Dwarves named it Durin's Bane and fled their halls forever. Khazad-dûm went dark, and Men called it Moria, the Black Chasm." },
  { id: "general-10", arc: "general", revealMiles: 880, x: 745, y: 429, title: "A Fallen Standing-Stone", story: "A great grey stone lies toppled in the heather, carved all over with runes worn far too smooth to read. It was raised by some people long gone, for some reason long forgotten. It makes a fine place to sit, catch your breath, and feel briefly small against the sheer age of the world." },
  { id: "wizards-4", arc: "wizards", revealMiles: 900, x: 873, y: 381, title: "Radagast the Brown", story: "Radagast the Brown loved the beasts and birds and green growing things above all else, and learned their tongues and their ways. Some said he strayed from his errand, lost among the wild woods and the wonder of hue and shape — but the birds and beasts he befriended carried word across Middle-earth when it was needed most. Even a wizard who wanders may serve without knowing it." },
  { id: "dwarves-4", arc: "dwarves", revealMiles: 912, x: 792, y: 468, title: "The Book of Mazarbul", story: "Long after, brave Balin led an expedition to retake the old kingdom, and for five bright years called himself Lord of Moria. Then the orcs came in their thousands. The last pages of their record are scrawled and blotted: “We cannot get out. The pool is up to the wall. Drums, drums in the deep. They are coming.” They found only silence, and a white tomb in the dark." },
  { id: "elves-3", arc: "elves", revealMiles: 935, x: 906, y: 440, title: "The Golden Wood", story: "In Lothlórien the mallorn-trees rise silver and gold, and no shadow falls; there Galadriel, mightiest of the Eldar remaining, guards the wood with Nenya, the Ring of Adamant. Time runs strange beneath the leaves — grief grows gentle, and the world outside feels a passing dream. Travelers who leave carry the ache of it forever, for they have walked in a memory of the world when it was young." },
  { id: "smeagol-5", arc: "smeagol", revealMiles: 955, x: 793, y: 467, title: "Two Words", story: "At last the hunger drove him out under the hated sky, tracking a scent grown cold with years. But other hunters walked abroad; they took him down into the Black Land and wrung him in the dark until two words tore loose — Shire. Baggins. Then they loosed the broken thing, for a creature that would lead them to the Ring was worth more free than caged." },
  { id: "elves-4", arc: "elves", revealMiles: 985, x: 908, y: 452, title: "The Light of Eärendil", story: "When the travelers left the Golden Wood, the Lady Galadriel gave each a parting gift, and to the Ring-bearer a small crystal phial. Within it was caught the light of Eärendil's star — the Mariner who sails the night sky forever with a Silmaril, holiest of the old jewels, bound upon his brow. “May it be a light to you in dark places,” she said, “when all other lights go out.” Even in the deepest dark, the Elves keep a little of the world's first morning." },
  { id: "bombadil-5", arc: "bombadil", revealMiles: 1000, x: 795, y: 477, title: "Old Man Willow", story: "At the green heart of the Old Forest grows Old Man Willow, huge and grey, with a cunning thirsty spirit under his bark and a drowsy song that lulls travelers to sleep — and then folds them fast into the cracks of his trunk. The trees of that wood hate all things that walk free, and he is their master and their malice. Only Tom knows the old willow's true name, and only Tom's singing can make him loose his roots and let his prey walk away." },
  { id: "general-11", arc: "general", revealMiles: 1010, x: 909, y: 457, title: "The Ferryman's Post", story: "A leaning post by the water still holds a frayed rope-end and a weathered sign: “Ring for the ferry.” There is no ferry, and no bell, and has not been for many long years. But someone has pinned a smaller note below it: “Find another way across — you always can.”" },
  { id: "elves-5", arc: "elves", revealMiles: 1045, x: 797, y: 487, title: "The Woodland Realm", story: "Northward lies Mirkwood, once Greenwood the Great, darkened for an age by a shadow that crept from a hidden tower in the south. Beneath its black boughs Thranduil's folk held their halls and their feasts and their long war with spiders and gloom. As the age turns, the Elves' time turns with it: the light wanes, and the grey ships wait in the West to carry them over Sea, out of Middle-earth forever." },
  { id: "general-12", arc: "general", revealMiles: 1080, x: 900, y: 447, title: "A Boat in the Reeds", story: "Drawn up among the reeds by the water lies a small grey boat of elven make, light as a leaf and quiet as a whisper, its lines curved like a swan's neck. There is no one near it, and no sign of where its owners went. It seems to be waiting, patiently, the way only elven things can wait." },
  { id: "bombadil-6", arc: "bombadil", revealMiles: 1100, x: 832, y: 538, title: "The Ring Means Nothing", story: "They say he took the Ring and laughed, spun it on his finger, and did not vanish — it had no power over him at all, and for a moment he even made it disappear as a joke. The Wise would not give it to him for keeping, though; not because he would fall to it, but because he would forget it, or toss it away, caring nothing for such things. Power over others was never his — only mastery of himself, and of merriment." },
  { id: "smeagol-6", arc: "smeagol", revealMiles: 1205, x: 926, y: 460, title: "The Promise on the Precious", story: "He trailed the company down the Great River, a log with eyes, a cough in the night — until in the grey rocks the hobbitses caught him. The new master, who bore the precious now, bound him with an elvish rope that burned, and Sméagol swore to serve the master of the Precious. He swore upon It, and it began to unmake him. He led them safe through the Dead Marshes, past the candles of the drowned. Not pushing them in. Not yet." },
  { id: "general-13", arc: "general", revealMiles: 1260, x: 920, y: 453, title: "A Beacon's Cold Ashes", story: "On a bare hilltop sits a ring of blackened stones, the ashes of an old warning-beacon long since cold and scattered by the wind. In better-guarded days a fire lit here would have leapt from hill to hill to summon aid. For now it is only a good place to see how far you have come — and how far there is still to go." },
  { id: "wizards-5", arc: "wizards", revealMiles: 1300, x: 956, y: 452, title: "The Blue Wizards", story: "Two of the five went east and south into lands the tales of the West do not follow — the Blue Wizards, Alatar and Pallando, who passed beyond the edge of every map and never returned. Whether they failed and fell, or founded strange cults, or kindled some quiet rebellion that kept the East from swelling Sauron's armies, no one in these lands can say. Their story simply walks off the page and is lost." },
  { id: "faramir-1", arc: "faramir", revealMiles: 1345, x: 1040, y: 548, title: "The Rangers of Ithilien", story: "In the debated land east of the River, Faramir and his green-clad rangers keep a secret war, striking the enemy's marches and slipping away like shadows among the trees. Younger son of the Steward, brother to bold Boromir, Faramir loves the White City not for its power but for its memory and its mercy. He is a captain who would rather heal than wound, and reads the old lore his father scorns." },
  { id: "bombadil-7", arc: "bombadil", revealMiles: 1360, x: 1034, y: 565, title: "Before the Dark Lord", story: "Tom remembers when there were no paths at all — when the hills were young, the river had not yet found the sea, and the stars were newly kindled overhead. He knew the acorn before the forest and the raindrop before the storm. “He knew the dark under the stars when it was fearless,” says Goldberry, “before the Dark Lord came from Outside” — and that is older than any tale the Elves or Men still remember." },
  { id: "faramir-2", arc: "faramir", revealMiles: 1420, x: 903, y: 627, title: "The Horn of Gondor", story: "Days before any messenger could have reached the city, Faramir kept a strange watch beside the River — and saw a little grey boat pass in the failing light, and in it his brother Boromir, cold and fair, girt with a broken sword. Upon his knees lay the cloven halves of the great Horn of Gondor, the horn that a son of the Steward carries and that is heard at need in the White City. Faramir knew then that his brother was dead, though he never could say how he knew." },
  { id: "smeagol-7", arc: "smeagol", revealMiles: 1470, x: 1032, y: 652, title: "Nice Master, Cruel Precious", story: "On the long climb two Sméagols argued without end. One wept, called the master nice, and longed to be a hobbit again; the other hissed that the master would keep the Precious for himself — that They should let Her have him, She who waits in the high dark, and take it back from what was left. Soft words on his tongue, murder behind his teeth, he led them up toward the spider's pass." },
  { id: "faramir-3", arc: "faramir", revealMiles: 1485, x: 917, y: 648, title: "The Window on the West", story: "When two small travelers strayed into his land, Faramir took them to Henneth Annûn, the hidden refuge behind the waterfall, and there guessed the terrible thing one of them carried. He might have seized it and borne it to his father in triumph — but he would not. “I would not take this thing, if it lay by the highway,” he said. “Not were Minas Tirith falling in ruin and I alone could save her.”" },
  { id: "bombadil-8", arc: "bombadil", revealMiles: 1520, x: 1042, y: 648, title: "The Oldest Names", story: "Every folk that ever crossed his little land gave Tom a different name. The Elves called him Iarwain Ben-adar — “Oldest and Fatherless.” The Dwarves said Forn; the Men of the North named him Orald. He answers to all of them and truly needs none, for the naming of things is the oldest and deepest lore of all, and Tom was there giving names, or hearing them, before there was anyone else left to remember." },
  { id: "general-14", arc: "general", revealMiles: 1550, x: 1089, y: 785, title: "A Milestone of the Kings", story: "An ancient stone stands half-swallowed by grass, carved with the worn device of a tree and seven stars — a milestone from the days when the Kings still rode these roads. The distance it once marked is long since rubbed away by rain and years. Still it stands, keeping faith with travelers whose names it never knew." },
  { id: "faramir-4", arc: "faramir", revealMiles: 1600, x: 1216, y: 818, title: "Not for the Praise of the Wise", story: "Where his brother had been tempted, Faramir let the Ring-bearer go free into the dark, and set two enemies of Sauron on their secret road with what aid he could. He did it knowing his father would call it folly, knowing he would win no praise for it. He loved courage that served mercy, not glory — and staked the fate of his city on the faith that a small, doomed errand was the wiser road." },
  { id: "smeagol-8", arc: "smeagol", revealMiles: 1620, x: 1252, y: 812, title: "Almost a Hobbit Again", story: "On the dark stairs below the spider's lair, Gollum crept back and found the hobbits asleep, the master's face gentle and unguarded. Something old and half-drowned stirred in him, and he reached out a trembling hand, almost tender, almost a hobbit again. Then Sam woke and spoke roughly, calling him sneak and thief — and the small warm thing curled up and died. After that there was only Her, and the plan, and the precious." },
  { id: "general-15", arc: "general", revealMiles: 1640, x: 1280, y: 806, title: "The Last Friendly Milestone", story: "An old milestone stands where the green country gives way to grey — the last one carved by friendly hands before the road runs on into harder lands. Someone has scratched a final message across its worn face: “Beyond here, keep your chin up and your feet moving. The way is dark, but it is not endless.”" },
  { id: "bombadil-9", arc: "bombadil", revealMiles: 1655, x: 1328, y: 720, title: "He Does Not Come Here", story: "Far away the world holds its breath over rings and wars and towers, but here nothing changes: Tom sings to the water, gathers lilies for Goldberry, and remembers ages no one else survives to name. He will not march to any battle, nor pass the bounds of his little land — such matters are not his. When all the great tales end, the Eldest will still be singing under the willows, as he was before they began." },
  { id: "orcs-1", arc: "orcs", revealMiles: 1670, x: 1204, y: 678, title: "Made in Mockery", story: "The orcs were not always so. In the deeps of time the first Dark Lord took living things and marred them — caged, tortured, and twisted over long ages until they came forth crooked and cruel, a mockery of fairer folk. Bred to hate the light and one another, they multiplied in the dark and served whatever whip drove them hardest. Even they, it is said, are a ruin of something that was once not evil." },
  { id: "orcs-2", arc: "orcs", revealMiles: 1695, x: 1300, y: 554, title: "The Uruk-hai", story: "Not all orcs are the small, cringing, sun-fearing kind. The Dark Lords bred greater ones — the Uruk-hai, black and tall, strong as Men and unafraid of open daylight, made for marching and killing and little else. They despise the lesser “snaga,” the slave-orcs, and drive them on with whips and curses. Reared in the breeding-pits to obey and to slaughter, they know nothing of home or craft or making — only the road, the whip, and blood." },
  { id: "orcs-3", arc: "orcs", revealMiles: 1720, x: 1169, y: 462, title: "The Big Bosses", story: "In the guardrooms of Mordor the common orcs grumble endlessly, hating the great Eye, the whip-hand of the Nazgûl, and every ‘big boss’ above them. “When it's all quiet,” one muttered, “I'd like to slip off with a few trusty lads, somewhere with good loot handy and no big bosses.” They fear their masters more than any enemy — and dream, in their small cruel way, of being free of them." },
  { id: "orcs-4", arc: "orcs", revealMiles: 1760, x: 1303, y: 277, title: "A Rag and a Bone", story: "For all their numbers, the orcs cannot keep faith even with each other. Set two of them over a prize — a fine shirt of mithril-mail, say, taken from a captive — and they will lie, betray, and cut each other down over it before any enemy arrives. More than once the Dark Lord's own servants did his enemies' work for them, slaughtering one another in the dark towers. Malice devours its own." },
  { id: "smeagol-9", arc: "smeagol", revealMiles: 1772, x: 1218, y: 168, title: "His at Last", story: "At the fire's very edge, where the Ring was forged, the master claimed the Precious and vanished from sight. But Gollum had clawed his way up the mountain too, for the pull of It never let him rest. He wrestled the unseen thing, bit the finger from its hand, and held the Ring aloft — his, his own, his birthday-present at last! — dancing too near the brink. Then he fell, gold and gollum together, into the fire, and saved the world by the very thing that damned him." },
];
